CADC-10865 - remove the global variables, refactor to MetaVisit approach
opencadc/gem2caom2 pull request #50
Opened 2022-02-09 01:01 UTC by SharonGoliath

2022-02-09 19:40 UTC, at88mph requested changes

2022-02-09 19:40 UTC, at88mph commented on gem2caom2/builder.py
> +        self._metadata.reader = self._metadata_reader
This (or the `_metadata_reader`) looks redundant.  Are both necessary?

2022-02-09 19:40 UTC, at88mph commented on gem2caom2/cleanup_augmentation.py
> +    result = {
Does this get used in a global way?  I can't see where it goes.

2022-02-09 19:40 UTC, at88mph commented on gem2caom2/preview_augmentation.py
> +    result = {'artifacts': count}
Now I assume this is getting used elsewhere. :)

2022-02-10 00:06 UTC, SharonGoliath commented on gem2caom2/builder.py
> +        self._metadata.reader = self._metadata_reader
The self._metadata class is for looking up values in JSON records retrieved from archive.gemini.edu.

The self._metadata_reader class is for retrieving the JSON records from archive.gemini.edu.

So, yes, both are necessary. Would you prefer different names?

2022-02-10 00:17 UTC, at88mph commented on gem2caom2/builder.py
> +        self._metadata.reader = self._metadata_reader
No.  If that object contained state I could see some code smell there.  Is it just a stateless reader?

2022-02-10 00:20 UTC, SharonGoliath commented on gem2caom2/preview_augmentation.py
> +    result = {'artifacts': count}
Not right now - see comment above.

2022-02-10 03:00 UTC, at88mph approved these changes

2022-02-11 00:57 UTC, SharonGoliath commented on gem2caom2/builder.py
> +        self._metadata.reader = self._metadata_reader
self._metadata is a stateless reader. Was that the data member you were referring to?

2022-02-11 00:57 UTC, merged